name: tool_base
description: Base for developing command line apps. Take from Flutter Tools.
version: 1.9.5+3
homepage: https://github.com/kstainke/tool_base

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: ^3.1.2
  file: ^6.1.2
  intl: ^0.17.0
  platform: ^3.0.0
  process: ^4.2.3
  pub_cache: ^0.3.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^5.0.16
  quiver: ^3.0.1+1
  file_testing: ^3.0.0
